#include "matching_engine.hpp"
#include <iostream>
#include <iomanip>
#include <chrono>
#include <cassert>

using namespace trading;
using namespace chaos_reflection;

void print_banner(const std::string& title) {
    std::cout << "\n" << std::string(70, '=') << "\n";
    std::cout << "  " << title << "\n";
    std::cout << std::string(70, '=') << "\n";
}

int main() {
    std::cout << "\n";
    std::cout << "######################################################################\n";
    std::cout << "#     CHAOS PREPROCESSOR - PRODUCTION TRADING ENGINE DEMO            #\n";
    std::cout << "#     Zero-Overhead Compile-Time Reflection & Serialization          #\n";
    std::cout << "######################################################################\n";

    // ========================================================================
    // Step 1: Compile-Time Reflection & Introspection
    // ========================================================================
    print_banner("1. COMPILE-TIME REFLECTION & FIELD INTROSPECTION");

    std::cout << "[*] Reflected Struct: trading::LimitOrder\n";
    std::cout << "    - Field count: " << LimitOrder::field_count << "\n";
    std::cout << "    - Field names: ";
    for (size_t i = 0; i < LimitOrder::field_names.size(); ++i) {
        if (i > 0) std::cout << ", ";
        std::cout << LimitOrder::field_names[i];
    }
    std::cout << "\n\n";

    // Create a production order instance
    LimitOrder order;
    order.order_id = 10042;
    order.client_ref = "ORD-20260921-9921";
    order.symbol = "BTC-USD";
    order.side = OrderSide::BUY;
    order.type = OrderType::LIMIT;
    order.tif = TimeInForce::GTC;
    order.quantity = 50;
    order.limit_price.units = 68500;
    order.limit_price.nanos = 250000000;
    order.limit_price.currency = Currency::USD;
    order.trader.trader_id = "TRADER_QUANT_01";
    order.trader.firm_id = "CITADEL_CORE";
    order.trader.desk_id = "CRYPTO_DESK_A";
    order.trader.is_market_maker = false;
    order.trader.max_credit_units = 10000000;
    order.status = OrderStatus::NEW;
    order.timestamp_epoch_ns = 1758464100123456789ULL;

    std::cout << "[*] Dynamic Field Visitor traversal (auto-generated by Chaos PP):\n";
    for_each_field(order, [](std::string_view name, const auto& val) {
        if constexpr (is_reflected_v<std::decay_t<decltype(val)>>) {
            std::cout << "    • " << std::left << std::setw(22) << name << " -> [Nested Reflected Struct]\n";
        } else if constexpr (std::is_enum_v<std::decay_t<decltype(val)>>) {
            std::cout << "    • " << std::left << std::setw(22) << name << " -> " << to_string(val) << " (Enum)\n";
        } else {
            std::cout << "    • " << std::left << std::setw(22) << name << " -> " << val << "\n";
        }
    });

    // ========================================================================
    // Step 2: Zero-Boilerplate JSON Serialization & Round-trip Deserialization
    // ========================================================================
    print_banner("2. JSON SERIALIZATION & ROUNDTRIP DESERIALIZATION");

    std::string json_output = to_json(order);
    std::cout << "[*] Auto-generated JSON serialization:\n" << json_output << "\n\n";

    LimitOrder deserialized_order;
    bool parse_ok = from_json(json_output, deserialized_order);
    assert(parse_ok);
    assert(order == deserialized_order);

    std::cout << "[+] Deserialization verification: SUCCESS\n";
    std::cout << "    Deep equality operator== check: " << (order == deserialized_order ? "MATCH" : "MISMATCH") << "\n";

    // ========================================================================
    // Step 3: Low-Latency Binary Wire Serialization & Deserialization
    // ========================================================================
    print_banner("3. LOW-LATENCY COMPACT BINARY PROTOCOL");

    std::vector<uint8_t> binary_wire;
    write_binary(binary_wire, order);

    std::cout << "[*] Serialized compact binary size: " << binary_wire.size() << " bytes\n";
    std::cout << "    (vs JSON size: " << json_output.size() << " bytes - "
              << (100 - (binary_wire.size() * 100 / json_output.size())) << "% reduction)\n";

    LimitOrder recovered_bin_order;
    const uint8_t* ptr = binary_wire.data();
    size_t len = binary_wire.size();
    bool bin_read_ok = read_binary(ptr, len, recovered_bin_order);

    assert(bin_read_ok);
    assert(len == 0);
    assert(order == recovered_bin_order);

    std::cout << "[+] Binary wire deserialization: SUCCESS (100% byte verification)\n";

    // ========================================================================
    // Step 4: Multi-Step Trading Workflow & Execution Report
    // ========================================================================
    print_banner("4. END-TO-END TRADING ENGINE WORKFLOW");

    RiskAndMatchingEngine engine;
    std::cout << "[*] Sending order " << order.client_ref << " to Risk & Matching Engine...\n";

    ExecutionReport report = engine.process_order(order);

    std::cout << "[+] Execution processed! Engine Latency: " << report.latency_ns << " ns\n";
    std::cout << "[+] Resulting ExecutionReport (JSON):\n" << to_json(report) << "\n";

    // ========================================================================
    // Step 5: High-Performance Production Microbenchmark
    // ========================================================================
    print_banner("5. HIGH-THROUGHPUT PRODUCTION MICROBENCHMARK (50,000 ORDERS)");

    constexpr size_t BENCHMARK_COUNT = 50000;
    std::cout << "[*] Running pipeline microbenchmark: " << BENCHMARK_COUNT << " orders...\n";
    std::cout << "    Each iteration performs:\n";
    std::cout << "      1. Pre-trade Risk Calculation & Credit Checks\n";
    std::cout << "      2. Multi-fill Matching Engine Simulation\n";
    std::cout << "      3. ExecutionReport Allocation\n";
    std::cout << "      4. Binary Wire Audit Journal Serialization\n\n";

    auto bench_start = std::chrono::steady_clock::now();

    for (size_t i = 0; i < BENCHMARK_COUNT; ++i) {
        LimitOrder bench_order;
        bench_order.order_id = 200000 + i;
        bench_order.client_ref = "BENCH_ORD";
        bench_order.symbol = "ETH-USD";
        bench_order.side = (i % 2 == 0) ? OrderSide::BUY : OrderSide::SELL;
        bench_order.type = OrderType::LIMIT;
        bench_order.tif = TimeInForce::DAY;
        bench_order.quantity = 10 + (i % 100);
        bench_order.limit_price.units = 3500;
        bench_order.limit_price.nanos = 0;
        bench_order.limit_price.currency = Currency::USD;
        bench_order.trader.trader_id = "BOT_ALGO";
        bench_order.trader.firm_id = "QUANT_LAB";
        bench_order.trader.desk_id = "PROP_1";
        bench_order.trader.is_market_maker = false;
        bench_order.trader.max_credit_units = 50000000;
        bench_order.status = OrderStatus::NEW;
        bench_order.timestamp_epoch_ns = 1758464200000000000ULL + i;

        engine.process_order(bench_order);
    }

    auto bench_end = std::chrono::steady_clock::now();
    uint64_t total_ns = std::chrono::duration_cast<std::chrono::nanoseconds>(bench_end - bench_start).count();

    EngineMetrics metrics = engine.compute_metrics(total_ns);

    std::cout << "[+] Microbenchmark Completed Successfully!\n";
    std::cout << "    - Total Audit Journal written: " << (engine.audit_journal_size() / (1024 * 1024)) << " MB\n";
    std::cout << "    - Engine Metrics (Reflected JSON):\n" << to_json(metrics) << "\n";

    std::cout << "\n######################################################################\n";
    std::cout << "#  PRODUCTION DEMO FINISHED SUCCESSFULLY WITH ZERO RUNTIME OVERHEAD  #\n";
    std::cout << "######################################################################\n\n";

    return 0;
}
